N.g.mapleader = ' '
N.g.maplocalleader = ' '

N.builtin.disable 'tar'
N.builtin.disable 'zip'
N.builtin.disable 'gzip'
N.builtin.disable 'netrw'
N.builtin.disable 'logipat'
N.builtin.disable 'matchit'
N.builtin.disable 'vimball'
N.builtin.disable 'rrhelper'
N.builtin.disable 'getscript'
N.builtin.disable 'tarPlugin'
N.builtin.disable 'zipPlugin'
N.builtin.disable 'matchparen'
N.builtin.disable 'netrwPlugin'
N.builtin.disable '2html_plugin'
N.builtin.disable 'netrwSettings'
N.builtin.disable 'vimballPlugin'
N.builtin.disable 'getscriptPlugin'
N.builtin.disable 'getscriptPlugin'
N.builtin.disable 'spellfile_plugin'
N.builtin.disable 'netrwFileHandlers'
